-- MySQL Script generated by MySQL Workbench
-- Fri Apr  8 14:51:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`postings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`postings` (
                                                     `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                     `mat_doc` BIGINT NOT NULL,
                                                     `item` BIGINT NOT NULL,
                                                     `doc_date` DATE NOT NULL,
                                                     `pstng_date` DATE NOT NULL,
                                                     `material_description` VARCHAR(255) NOT NULL,
    `quantity` BIGINT NOT NULL,
    `b_un` VARCHAR(255) NOT NULL,
    `amount_lc` DECIMAL NOT NULL,
    `crcy` VARCHAR(255) NOT NULL,
    `user_name` VARCHAR(255) NOT NULL,
    `authorized_delivery` TINYINT NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`logins` (
                                                   `login_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                   `application` VARCHAR(255) NOT NULL,
    `app_account_name` VARCHAR(255) NOT NULL,
    `is_active` TINYINT NOT NULL,
    `job_title` VARCHAR(255) NOT NULL,
    `department` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`login_id`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
